const primary = "#1A56DB";
const primaryDark = "#1E40AF";
const success = "#10B981";
const warning = "#F59E0B";
const danger = "#EF4444";

export default {
  light: {
    primary,
    primaryDark,
    success,
    warning,
    danger,
    text: "#0F172A",
    textSecondary: "#475569",
    textMuted: "#94A3B8",
    background: "#F8FAFC",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    border: "#E2E8F0",
    borderLight: "#F1F5F9",
    tint: primary,
    tabIconDefault: "#94A3B8",
    tabIconSelected: primary,
    badge: "#EF4444",
    inputBackground: "#F8FAFC",
    skeleton: "#E2E8F0",
    skeletonHighlight: "#F1F5F9",
    statusOpen: "#DBEAFE",
    statusOpenText: "#1D4ED8",
    statusAssigned: "#FEF9C3",
    statusAssignedText: "#A16207",
    statusInTransit: "#DBEAFE",
    statusInTransitText: "#1D4ED8",
    statusDelivered: "#D1FAE5",
    statusDeliveredText: "#065F46",
    statusCancelled: "#FEE2E2",
    statusCancelledText: "#991B1B",
  },
  dark: {
    primary,
    primaryDark,
    success,
    warning,
    danger,
    text: "#F1F5F9",
    textSecondary: "#94A3B8",
    textMuted: "#64748B",
    background: "#0F172A",
    surface: "#1E293B",
    surfaceElevated: "#1E293B",
    border: "#334155",
    borderLight: "#1E293B",
    tint: primary,
    tabIconDefault: "#64748B",
    tabIconSelected: primary,
    badge: "#EF4444",
    inputBackground: "#1E293B",
    skeleton: "#334155",
    skeletonHighlight: "#475569",
    statusOpen: "#1E3A5F",
    statusOpenText: "#93C5FD",
    statusAssigned: "#3B2A04",
    statusAssignedText: "#FDE68A",
    statusInTransit: "#1E3A5F",
    statusInTransitText: "#93C5FD",
    statusDelivered: "#064E3B",
    statusDeliveredText: "#6EE7B7",
    statusCancelled: "#450A0A",
    statusCancelledText: "#FCA5A5",
  },
};
